version: "3"
services:
  cifar10-classifier:
    container_name: cifar10-classifier-container
    image: cifar10-classifier-image
    build:
      context: .
      dockerfile: dockerfile

    # Volumns
    volumes:
        - .:/workspace
    
    # Easy to use network
    network_mode: host

    # Inter-process communication
    ipc: host

    # Nvidia driver
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    # Interactive mode
    stdin_open: true
    tty: true
    entrypoint: "/bin/bash"